// scripts/converters-data.js
// Data definitions for channel metric converter pages
// Add a new entry → run `node scripts/generate-converters.mjs` → deployed

const converters = [
  {
    id: 'views-to-revenue',
    name: 'YouTube Views to Revenue Calculator',
    slug: 'views-to-revenue',
    description: 'Estimate how much money your YouTube videos make based on views, CPM, and niche.',
    metaDesc: 'Free YouTube revenue calculator. Estimate earnings from views based on your niche, CPM rate, and engagement. See how much YouTubers really make per 1,000 views.',
    h1: 'YouTube Revenue Calculator: How Much Do Views Pay?',
    inputs: [
      { id: 'views', label: 'Monthly Views', type: 'number', default: '10000', placeholder: 'e.g. 10000', min: 0, step: '1000' },
      { id: 'cpm', label: 'Estimated CPM ($)', type: 'number', default: '3.50', placeholder: 'e.g. 3.50', min: 0, step: '0.25', info: 'CPM varies by niche. Gaming ~$2, Education ~$5, Finance ~$15' },
      { id: 'ctr', label: 'Click-Through Rate (%)', type: 'number', default: '5', placeholder: 'e.g. 5', min: 0, max: 100, step: '0.5', info: 'Average CTR is 2-10%. Higher is better.' },
    ],
    formula: '(views * cpm / 1000) * (ctr / 5)',
    explainer: 'YouTube pays based on CPM (cost per 1,000 monetized views). Not all views are monetized. The CTR factor adjusts for estimated monetizable view rate.',
    niches: [
      { name: 'Gaming', cpm: 2.00, icon: '🎮' },
      { name: 'Education', cpm: 5.00, icon: '📚' },
      { name: 'Tech Reviews', cpm: 8.00, icon: '💻' },
      { name: 'Finance', cpm: 15.00, icon: '📈' },
      { name: 'Lifestyle', cpm: 3.50, icon: '✨' },
      { name: 'Music', cpm: 1.50, icon: '🎵' },
    ],
    category: 'Revenue',
    related: ['subs-to-views', 'ctr-calculator', 'video-length-optimizer'],
  },
  {
    id: 'subs-to-views',
    name: 'Subscriber to View Estimator',
    slug: 'subs-to-views',
    description: 'Estimate how many daily views your channel gets based on subscriber count and engagement rate.',
    metaDesc: 'Free YouTube view estimator. Predict daily and monthly views from your subscriber count and engagement rate. How many views should X subs get?',
    h1: 'YouTube View Estimator: Views per Subscriber',
    inputs: [
      { id: 'subs', label: 'Subscribers', type: 'number', default: '10000', placeholder: 'e.g. 10000', min: 0, step: '1000' },
      { id: 'engagement', label: 'Engagement Rate (%)', type: 'number', default: '8', placeholder: 'e.g. 8', min: 0, max: 100, step: '0.5', info: 'Views per subscriber per month. Average: 5-15% for active channels' },
      { id: 'videosPerMonth', label: 'Videos per Month', type: 'number', default: '8', placeholder: 'e.g. 8', min: 1, step: '1' },
    ],
    formula: '(subs * engagement / 100) * videosPerMonth',
    explainer: 'Most channels get 5-15% of their subscribers viewing each video in the first month. This calculator estimates total monthly views based on your subscriber engagement rate.',
    niches: [
      { name: 'Small Channel', subs: 1000, engagement: 12, icon: '🌱' },
      { name: 'Growing Channel', subs: 10000, engagement: 8, icon: '📈' },
      { name: 'Mid-Size', subs: 100000, engagement: 6, icon: '🔥' },
      { name: 'Large Channel', subs: 1000000, engagement: 4, icon: '⭐' },
    ],
    category: 'Growth',
    related: ['views-to-revenue', 'ctr-calculator', 'video-length-optimizer'],
  },
  {
    id: 'ctr-calculator',
    name: 'YouTube CTR & Traffic Calculator',
    slug: 'ctr-calculator',
    description: 'Calculate impressions, CTR, and traffic from your YouTube analytics data.',
    metaDesc: 'Free YouTube CTR calculator. Calculate impressions needed for target views, or views from impressions and CTR. Optimize your thumbnail and title performance.',
    h1: 'YouTube CTR Calculator: Impressions & Traffic',
    inputs: [
      { id: 'impressions', label: 'Impressions', type: 'number', default: '100000', placeholder: 'e.g. 100000', min: 0, step: '10000' },
      { id: 'ctr', label: 'CTR (%)', type: 'number', default: '5', placeholder: 'e.g. 5', min: 0, max: 100, step: '0.1' },
    ],
    formula: 'impressions * ctr / 100',
    explainer: 'CTR (click-through rate) is the percentage of people who click your video after seeing an impression. YouTube average CTR is 2-10%. Thumbnails and titles are the biggest CTR drivers.',
    niches: [
      { name: 'Poor CTR', ctr: 2, icon: '⚠️', desc: 'Needs thumbnail/title work' },
      { name: 'Average CTR', ctr: 5, icon: '👌', desc: 'Decent performance' },
      { name: 'Good CTR', ctr: 8, icon: '✅', desc: 'Strong thumbnail/title' },
      { name: 'Viral CTR', ctr: 15, icon: '🚀', desc: 'Exceptional engagement' },
    ],
    category: 'Analytics',
    related: ['views-to-revenue', 'subs-to-views', 'video-length-optimizer'],
  },
  {
    id: 'video-length-optimizer',
    name: 'YouTube Video Length Optimizer',
    slug: 'video-length-optimizer',
    description: 'Find the optimal video length for your content type to maximize retention and watch time.',
    metaDesc: 'Free YouTube video length optimizer. Find the ideal video duration for your niche and content type to maximize retention, watch time, and algorithm performance.',
    h1: 'YouTube Video Length Optimizer: Best Duration by Niche',
    inputs: [
      { id: 'niche', label: 'Content Type', type: 'select', options: [
        { value: 'tutorial', label: 'Tutorial / How-To' },
        { value: 'review', label: 'Product Review' },
        { value: 'vlog', label: 'Vlog / Lifestyle' },
        { value: 'gaming', label: 'Gaming' },
        { value: 'educational', label: 'Educational / Documentary' },
        { value: 'shorts', label: 'Shorts / Short Form' },
        { value: 'podcast', label: 'Podcast / Interview' },
      ], default: 'tutorial' },
      { id: 'retention', label: 'Current Avg Retention (%)', type: 'number', default: '40', placeholder: 'e.g. 40', min: 0, max: 100, step: '5', info: 'Average percentage of video watched' },
    ],
    formula: 'nicheOptimalLength * (retention / 40)',
    explainer: 'YouTube favors videos that retain viewers. Optimal length varies by niche. The formula adjusts the recommended length based on your current retention rate.',
    niches: [
      { name: 'Tutorial', length: '8-12 min', icon: '📖' },
      { name: 'Review', length: '6-10 min', icon: '🔍' },
      { name: 'Vlog', length: '8-15 min', icon: '🎬' },
      { name: 'Gaming', length: '10-20 min', icon: '🎮' },
      { name: 'Educational', length: '12-20 min', icon: '📚' },
      { name: 'Shorts', length: '15-60 sec', icon: '📱' },
      { name: 'Podcast', length: '20-60 min', icon: '🎙️' },
    ],
    category: 'Strategy',
    related: ['ctr-calculator', 'subs-to-views', 'views-to-revenue'],
  },
];

export default converters;