// scripts/guides-data.js
// How-to guide definitions — Wise-style "Code Guides" equivalent
// Each guide is a how-to page for a specific YT SEO Architect tool

const guides = [
  {
    id: 'tag-generator',
    name: 'YouTube Tag Generator',
    slug: 'tag-generator',
    description: 'Learn how to use the YouTube Tag Generator to find high-ranking tags, analyze competitor tags, and boost your video discoverability.',
    metaDesc: 'Step-by-step guide to using the YT SEO Architect Tag Generator. Learn to find high-ranking YouTube tags, analyze competitors, and boost video SEO with AI-optimized tags.',
    h1: 'How to Use the YouTube Tag Generator (2026 Guide)',
    sections: [
      { heading: 'What Is the YouTube Tag Generator?', content: 'The YT SEO Architect Tag Generator is a free AI-powered tool that analyzes your video topic and suggests the best performing tags. Unlike manual tag research, it scans YouTube\'s search data to find tags that actually drive views.' },
      { heading: 'Step 1: Enter Your Target Keyword', content: 'Start by entering your main keyword or video topic. The tool works best with specific phrases (e.g., "how to edit YouTube videos" rather than just "editing"). Be as precise as possible — the AI uses this to understand your content context.' },
      { heading: 'Step 2: Review Suggested Tags', content: 'The generator returns 10-15 optimized tags sorted by relevance. Each tag shows a search volume indicator. Focus on including the high-volume primary tags in your first 3-4 tag slots — YouTube weights these most heavily for ranking.' },
      { heading: 'Step 3: Mix Short and Long-Tail Tags', content: 'Use a mix of broad tags (1-2 words) and specific long-tail tags (3-5 words). Broad tags cast a wide net. Long-tail tags have lower competition and higher conversion rates. The tool automatically provides this mix.' },
      { heading: 'Step 4: Copy and Paste into YouTube Studio', content: 'Once satisfied, click "Copy All Tags" and paste them into your YouTube video\'s tags field in YouTube Studio. Tags should be comma-separated. The tool formats them correctly automatically.' },
      { heading: 'Pro Tips for Better Results', content: 'Use the Tag Relevance Checker alongside the generator to validate your chosen tags. Re-run the generator after publishing — YouTube\'s algorithm takes 24-48 hours to index new tags. Update tags monthly for older videos to refresh their ranking signals.' },
    ],
    faq: [
      { q: 'How many tags should I use on YouTube?', a: 'YouTube allows up to 500 characters of tags. Aim for 10-15 relevant tags totaling 200-300 characters. Quality over quantity — irrelevant tags can hurt your ranking.' },
      { q: 'Do YouTube tags still matter in 2026?', a: 'Yes. While YouTube\'s AI has improved, tags still help the algorithm understand your content context, especially for new channels building authority.' },
      { q: 'Can I use the same tags for every video?', a: 'No. Each video should have unique, relevant tags. Using the same tags across all videos signals spam to YouTube and can reduce your overall channel authority.' },
    ],
    toolLink: '/tools/tag-generator',
    toolCta: 'Open Tag Generator',
    related: ['title-optimizer', 'description-writer', 'keyword-difficulty-scorer'],
  },
  {
    id: 'title-optimizer',
    name: 'YouTube Title Optimizer',
    slug: 'title-optimizer',
    description: 'Learn how to use the YouTube Title Optimizer to write clickable, SEO-friendly titles that rank higher and get more clicks.',
    metaDesc: 'Complete guide to using the YT SEO Architect Title Optimizer. Learn to write clickable YouTube titles with AI-powered CTR analysis, keyword placement, and emotional trigger scoring.',
    h1: 'How to Use the YouTube Title Optimizer (2026 Guide)',
    sections: [
      { heading: 'What Is the Title Optimizer?', content: 'The Title Optimizer is an AI tool that analyzes your YouTube video titles for SEO performance, click-through rate potential, and keyword effectiveness. It scores your title and suggests improvements based on what\'s currently working in your niche.' },
      { heading: 'Step 1: Enter Your Current or Draft Title', content: 'Type or paste your video title into the optimizer. Include your target keyword naturally. The tool analyzes titles up to 100 characters (YouTube\'s display limit for search results).' },
      { heading: 'Step 2: Review Your Title Score', content: 'The tool returns a score out of 100 based on: keyword placement (front-loaded is better), length optimization (40-70 characters ideal), emotional trigger words, and power word usage. Scores above 70 are good; above 85 are excellent.' },
      { heading: 'Step 3: Apply Suggested Improvements', content: 'The optimizer highlights specific changes: move your keyword closer to the front, add power words (like "ultimate," "essential," "2026"), adjust character count, and improve emotional resonance. Each suggestion includes a reason why it matters.' },
      { heading: 'Step 4: A/B Test Your Final Titles', content: 'Use the Title A/B Tester tool to compare up to 3 title variations side by side. The tool predicts which version will get the highest CTR based on historical patterns from similar videos in your niche.' },
      { heading: 'Pro Tips for Better Titles', content: 'Include numbers (lists perform 36% better). Use brackets or parentheses for additional context [Tutorial 2026]. Front-load your keyword within the first 40 characters. Test different emotional angles — curiosity vs. urgency vs. value.' },
    ],
    faq: [
      { q: 'What is the ideal YouTube title length?', a: 'The ideal title length is 40-70 characters (or roughly 5-9 words). Titles this length perform best in search and display fully on all devices without truncation.' },
      { q: 'Should I put my keyword at the beginning of the title?', a: 'Yes. Front-loading your primary keyword signals relevance to YouTube\'s algorithm and increases the chance of ranking for that search term.' },
      { q: 'How often should I update my video titles?', a: 'Review titles after 2-4 weeks. If CTR is below 5%, try a new angle. Use the Title Optimizer to test variations before updating.' },
    ],
    toolLink: '/tools/title-optimizer',
    toolCta: 'Open Title Optimizer',
    related: ['tag-generator', 'description-writer', 'title-ab-tester'],
  },
  {
    id: 'description-writer',
    name: 'YouTube Description Writer',
    slug: 'description-writer',
    description: 'Learn how to use the YouTube Description Writer to craft SEO-optimized video descriptions that rank and convert.',
    metaDesc: 'Step-by-step guide to using the YT SEO Architect Description Writer. Write SEO-optimized YouTube descriptions with keyword placement, timestamps, CTAs, and affiliate links that rank.',
    h1: 'How to Use the YouTube Description Writer (2026 Guide)',
    sections: [
      { heading: 'What Is the Description Writer?', content: 'The Description Writer is an AI tool that generates complete YouTube video descriptions optimized for search. It handles keyword placement, timestamp structure, CTA placement, and affiliate link integration — everything a manual description needs.' },
      { heading: 'Step 1: Enter Your Video Topic', content: 'Provide your video title or main topic. The more specific you are, the better the generated description will match your content. Include 2-3 secondary keywords you want to target in the description.' },
      { heading: 'Step 2: Choose Your Description Style', content: 'Select from templates: Standard (balanced SEO + readability), Timestamp-Focused (heavy on chapter markers), CTA-Optimized (prioritizes engagement hooks), or Affiliate (includes product link sections naturally).' },
      { heading: 'Step 3: Customize the Generated Description', content: 'The AI generates a 200-500 word description. Review and customize: add your affiliate links, adjust the tone to match your brand voice, verify timestamps are accurate, and ensure the first 2 lines hook viewers (this is what shows in search results).' },
      { heading: 'Step 4: Add Timestamps and CTAs', content: 'Include 3-5 timestamped chapters with descriptive titles. Place your primary CTA (Subscribe, Watch Next) within the first 3 lines. Add 2-3 secondary CTAs throughout (Comment, Follow on Social).' },
      { heading: 'Pro Tips for Better Descriptions', content: 'Always put your target keyword in the first 2 lines. Use 1-2 relevant hashtags (not 15 — that looks spammy). Include a "Tools & Resources" section for affiliate links. Update old video descriptions quarterly to refresh SEO signals.' },
    ],
    faq: [
      { q: 'How long should a YouTube description be?', a: '200-500 words is ideal. The first 2 lines (roughly 150 characters) are critical — this is what shows in YouTube search results. Put your key info and CTA here.' },
      { q: 'Do descriptions really help with YouTube SEO?', a: 'Yes. Descriptions are one of the top 3 ranking signals YouTube uses. A well-optimized description helps the algorithm understand your content and match it to search queries.' },
      { q: 'Should I use the same description template for every video?', a: 'Use the same structure (hook, timestamps, CTA, resources) but customize the content. YouTube penalizes duplicate or recycled descriptions across videos.' },
    ],
    toolLink: '/tools/description-writer',
    toolCta: 'Open Description Writer',
    related: ['tag-generator', 'title-optimizer', 'title-ab-tester'],
  },
  {
    id: 'channel-audit',
    name: 'YouTube Channel Audit Tool',
    slug: 'channel-audit',
    description: 'Learn how to use the Channel Audit Tool to diagnose your YouTube channel with a 17-point metadata audit.',
    metaDesc: 'Complete guide to the YT SEO Architect Channel Audit. Run a 17-point YouTube channel audit to diagnose metadata issues, find optimization opportunities, and boost your search ranking.',
    h1: 'How to Run a YouTube Channel Audit (17-Point Check)',
    sections: [
      { heading: 'What Is the Channel Audit Tool?', content: 'The Channel Audit Tool runs a 17-point diagnostic scan of your YouTube channel metadata. It checks everything from title optimization and tag usage to description quality, thumbnail consistency, and playlist structure. Think of it as a health check for your channel\'s SEO.' },
      { heading: 'Step 1: Enter Your Channel URL', content: 'Paste your YouTube channel URL or handle. The tool analyzes publicly available metadata — no login required. Results generate in 30-60 seconds.' },
      { heading: 'Step 2: Review Your Audit Score', content: 'Your channel receives a score out of 100 across 17 checkpoints. Scores below 60 need immediate attention. The report highlights exactly which checkpoints failed and why, with specific recommendations for each.' },
      { heading: 'Step 3: Fix Critical Issues First', content: 'The audit prioritizes issues by impact. Start with "Critical" items (missing metadata, broken links) before addressing "Improvement" items (weak descriptions, inconsistent thumbnails). Each recommendation includes a step-by-step fix.' },
      { heading: 'Step 4: Track Improvements Over Time', content: 'Re-run the audit monthly to track your score improvement. The tool saves your last 5 results so you can see progress. Most channels see a 20-30 point improvement within 2 weeks of applying recommendations.' },
      { heading: 'Pro Tips for a Perfect Audit Score', content: 'Fix your channel trailer first (highest impact). Ensure every video has custom thumbnails (channels without them lose 30%+ potential CTR). Use consistent branding across banner, avatar, and thumbnails. Organize videos into topical playlists.' },
    ],
    faq: [
      { q: 'What does the 17-point audit check?', a: 'It checks: channel name optimization, description keyword usage, banner design, avatar consistency, trailer effectiveness, playlist structure, video title quality, tag usage, description completeness, thumbnail consistency, upload frequency, engagement rates, community tab activity, about section completeness, links setup, branding watermark, and content categorization.' },
      { q: 'Is the channel audit free?', a: 'Yes. The 17-point Channel Audit is completely free with no usage limits. Run it as often as you want to track your improvement.' },
      { q: 'How often should I audit my channel?', a: 'Run an audit monthly. Also run one after any major channel changes (rebranding, niche shift, or after implementing previous audit recommendations).' },
    ],
    toolLink: '/tools/channel-audit-score',
    toolCta: 'Run Channel Audit',
    related: ['title-optimizer', 'tag-generator', 'description-writer'],
  },
  {
    id: 'thumbnail-color-analyzer',
    name: 'YouTube Thumbnail Color Analyzer',
    slug: 'thumbnail-color-analyzer',
    description: 'Learn how to use the Thumbnail Color Analyzer to pick winning thumbnail colors that drive higher CTR.',
    metaDesc: 'Guide to using the YT SEO Architect Thumbnail Color Analyzer. Learn which colors drive the highest CTR on YouTube thumbnails, analyze your thumbnail color schemes, and optimize for more clicks.',
    h1: 'How to Use the Thumbnail Color Analyzer for Higher CTR',
    sections: [
      { heading: 'What Is the Thumbnail Color Analyzer?', content: 'The Thumbnail Color Analyzer evaluates your YouTube thumbnail\'s color scheme against proven CTR patterns. It analyzes contrast, color psychology, text readability, and visual hierarchy — scoring your thumbnail\'s likely performance.' },
      { heading: 'Step 1: Upload or Link Your Thumbnail', content: 'Upload a thumbnail image or paste a video URL. The tool extracts and analyzes the thumbnail automatically. For best results, use the highest resolution version available.' },
      { heading: 'Step 2: Review Your Color Score', content: 'Your thumbnail receives a color effectiveness score. The tool identifies: dominant colors and their emotional impact, contrast ratio between text and background, color harmony (complementary vs. clashing schemes), and attention-grabbing hotspots.' },
      { heading: 'Step 3: Apply Color Recommendations', content: 'The analyzer suggests specific improvements: increase contrast between your subject and background, use complementary color combinations (blue/orange, red/green), ensure text is readable at mobile thumbnail size (180x180px), and add accent colors for attention.' },
      { heading: 'Step 4: A/B Test Color Variations', content: 'Create 2-3 thumbnail variations with different color schemes. Use the analyzer to score each one. Publish the highest-scoring version, then run a YouTube thumbnail A/B test to confirm real-world performance.' },
      { heading: 'Pro Tips for Winning Thumbnail Colors', content: 'Red and orange drive urgency (highest CTR for tutorials). Blue builds trust (best for educational content). Yellow pops against dark backgrounds (great for gaming). High contrast between subject and background is the single most important factor.' },
    ],
    faq: [
      { q: 'What colors perform best on YouTube thumbnails?', a: 'Red, orange, and yellow tend to drive the highest CTR because they create urgency and stand out in search results. However, the best color depends on your niche and content type.' },
      { q: 'Should I use the same color scheme for all thumbnails?', a: 'Yes — brand consistency helps viewers recognize your content in search results. Use a consistent accent color (e.g., always use red for your text or borders) while varying the main background colors.' },
      { q: 'How important is thumbnail color for CTR?', a: 'Extremely important. Color contrast is the #1 factor in thumbnail CTR. A high-contrast thumbnail can get 2x the clicks of a low-contrast one, even with identical content.' },
    ],
    toolLink: '/tools/thumbnail-color-analyzer',
    toolCta: 'Open Color Analyzer',
    related: ['title-optimizer', 'tag-generator', 'title-ab-tester'],
  },
  {
    id: 'keyword-difficulty-scorer',
    name: 'YouTube Keyword Difficulty Scorer',
    slug: 'keyword-difficulty-scorer',
    description: 'Learn how to use the Keyword Difficulty Scorer to find low-competition keywords your channel can rank for.',
    metaDesc: 'Complete guide to the YT SEO Architect Keyword Difficulty Scorer. Learn to find low-competition YouTube keywords, analyze ranking difficulty, and target search terms your channel can actually rank for.',
    h1: 'How to Use the Keyword Difficulty Scorer (Find Easy-to-Rank Keywords)',
    sections: [
      { heading: 'What Is the Keyword Difficulty Scorer?', content: 'The Keyword Difficulty Scorer analyzes how hard it would be to rank for a specific YouTube keyword based on competition metrics. It considers channel authority of current top-ranking videos, optimized title/tag usage, view counts, and engagement rates of competitors.' },
      { heading: 'Step 1: Enter a Keyword Idea', content: 'Type a keyword or phrase you want to rank for. The tool works best with specific long-tail keywords (4-6 words) rather than broad short-tail terms. A keyword like "how to edit YouTube videos for beginners" will score differently than "video editing."' },
      { heading: 'Step 2: Review the Difficulty Score', content: 'Keywords score from 0-100. 0-30: Easy to rank (ideal for new channels). 30-60: Medium difficulty (good for growing channels). 60-100: Highly competitive (established channels only). The tool also shows why the keyword scored what it did.' },
      { heading: 'Step 3: Compare Multiple Keywords', content: 'Enter several keyword ideas for the same video topic. Compare their difficulty scores side by side. Pick the keyword with the best balance of search volume (shown via volume indicator) and low difficulty score.' },
      { heading: 'Step 4: Create Content Around Your Chosen Keyword', content: 'Once you\'ve selected a target keyword, use the Title Optimizer and Description Writer to create optimized content around it. Target 1 primary keyword and 2-3 secondary keywords per video.' },
      { heading: 'Pro Tips for Keyword Research', content: 'Target keywords with difficulty under 40 for channels under 1,000 subscribers. Mix 1 competitive keyword (to dream) with 2-3 easy keywords (to win) per video. Re-check keyword difficulty monthly — it changes as competitors publish new content.' },
    ],
    faq: [
      { q: 'What is a good keyword difficulty score?', a: 'For new channels, target scores under 30. For established channels (1K-10K subs), target under 50. For large channels, scores up to 70 are feasible. Above 70 is typically only achievable by top-tier channels.' },
      { q: 'How does the difficulty score work?', a: 'The score analyzes the top 10 ranking videos for your keyword, checking: average channel subscriber count, view counts, title/tag optimization level, description quality, and engagement rates. Higher competition in these areas = higher difficulty score.' },
      { q: 'Can I rank for high-difficulty keywords as a small channel?', a: 'Yes, by targeting long-tail variations. Instead of "YouTube SEO," target "YouTube SEO for small channels 2026" — much lower difficulty, same audience intent.' },
    ],
    toolLink: '/tools/keyword-difficulty-scorer',
    toolCta: 'Open Keyword Scorer',
    related: ['tag-generator', 'title-optimizer', 'description-writer'],
  },
];

export default guides;