// scripts/niches-data.js
// Niche guide definitions — Wise-style "Location Pages" equivalent

const niches = [
  {
    id: 'gaming', name: 'Gaming Channels', icon: '🎮',
    description: 'YouTube SEO strategies specifically for gaming channels — Let\'s Plays, walkthroughs, esports highlights, and gaming commentary.',
    metaDesc: 'YouTube SEO for gaming channels: optimize Let\'s Plays, walkthroughs, and esports content. Tips on tags, thumbnails, titles, and descriptions that rank in 2026.',
    h1: 'YouTube SEO for Gaming Channels: The 2026 Guide',
    intro: 'Gaming is one of the most competitive niches on YouTube. With thousands of new gaming videos uploaded every hour, standing out requires more than just good gameplay — you need strategic SEO. This guide covers everything from keyword research for game titles to thumbnail strategies that drive clicks in a crowded market.',
    tips: [
      { title: 'Target Game + Keyword Combinations', content: 'Don\'t just use the game name as your keyword. Combine it with search intent: "Minecraft survival tips," "Elden Ring boss guide," "Valorant rank up strategies." These long-tail keywords face less competition from established creators.' },
      { title: 'Optimize for Search vs Browse', content: 'Gaming viewers find content two ways: search (looking for specific game help) and browse (browsing homepage/recommended). Title optimization matters more for search; thumbnail clickability matters more for browse. Do both well.' },
      { title: 'Use Episode Numbers in Titles', content: 'For Let\'s Plays and series, include episode numbers in titles. This helps returning viewers find the next episode and signals to YouTube that your content is part of a bingeable series — boosting recommended traffic.' },
      { title: 'Thumbnail Strategies for Gaming', content: 'Gaming thumbnails need to stand out in a sea of similar content. Use bright colors, clear text overlays (2-3 words max), expressive face reactions, and in-game moments that create curiosity. A/B test 2-3 thumbnail variants per video.' },
      { title: 'Leverage Game-Specific Tags', content: 'Include the exact game title, developer, and related game terms in your tags. Also add niche-specific tags like "walkthrough," "gameplay," "no commentary," "live stream" depending on your content type.' },
      { title: 'Post Consistently for Algorithm Boost', content: 'The gaming algorithm favors channels that post regularly. Aim for 3-5 videos per week. Use YouTube\'s "Schedule" feature to maintain consistency even if you batch-record content on weekends.' },
    ],
    stats: { avgCtr: '6-9%', bestLength: '10-20 min', topKeywords: 'game name + guide/walkthrough/gameplay', avgCpm: '$2.00' },
    related: ['music', 'tech-reviews', 'fitness'],
  },
  {
    id: 'cooking', name: 'Cooking & Food Channels', icon: '🍳',
    description: 'YouTube SEO for cooking channels — recipe videos, kitchen tips, food reviews, and meal prep content.',
    metaDesc: 'YouTube SEO for cooking channels: optimize recipe videos, food reviews, and cooking tutorials. Tips on recipe keywords, video structure, and thumbnail strategies that rank.',
    h1: 'YouTube SEO for Cooking Channels: The 2026 Guide',
    intro: 'Food content is enormously popular on YouTube, but competition is fierce. From recipe tutorials to food reviews and kitchen gadget tests, success depends on getting your videos found. This guide breaks down SEO strategies specific to cooking and food content.',
    tips: [
      { title: 'Put the Dish Name in Your Title First', content: 'Start your title with the recipe or dish name — "Creamy Garlic Pasta in 15 Minutes" outperforms "How to Make Quick Pasta." Viewers search for dish names, not cooking techniques. Front-load the food name within the first 40 characters.' },
      { title: 'Use Recipe Keywords in Description', content: 'Include all ingredients, cooking times, and dietary tags (vegan, gluten-free, keto) in your description. This helps YouTube match your video to recipe searches. Structure your description with clear timestamps for each cooking step.' },
      { title: 'Close-Up Thumbnails Drive Clicks', content: 'Cooking thumbnails with close-up shots of the finished dish perform 40% better than wide shots. Use warm, appetizing colors (reds, oranges, golds). Add text overlays with the dish name in a bold, readable font.' },
      { title: 'Optimize for How-To and Recipe Searches', content: 'Cooking videos rank for two types of searches: specific recipes ("chicken tikka masala recipe") and technique queries ("how to knead dough"). Create separate videos optimized for each type rather than combining them.' },
      { title: 'Use Dietary Tags for Discovery', content: 'Include dietary labels in your title, description, and tags: "vegan," "gluten-free," "keto," "low-carb," "high-protein." These are highly searched modifiers that can dramatically expand your reach.' },
      { title: 'Film in Square or Vertical Format for Shorts', content: 'Cooking content performs exceptionally well as YouTube Shorts. Film vertical clips of key cooking moments — sizzling pans, pouring sauces, final plating — and post them as Shorts to drive channel discovery.' },
    ],
    stats: { avgCtr: '7-10%', bestLength: '6-12 min', topKeywords: 'recipe name + recipe/how to make/easy', avgCpm: '$3.50' },
    related: ['fitness', 'lifestyle', 'education'],
  },
  {
    id: 'music', name: 'Music Channels', icon: '🎵',
    description: 'YouTube SEO for music channels — original songs, covers, music production tutorials, and artist promotion.',
    metaDesc: 'YouTube SEO for music channels: optimize original songs, covers, and music tutorials. Tips on music keywords, YouTube Music search, cover song policies, and growing your audience.',
    h1: 'YouTube SEO for Music Channels: The 2026 Guide',
    intro: 'Music is one of YouTube\'s largest categories, but standing out as an independent artist requires smart SEO. Whether you upload original songs, covers, or production tutorials, these strategies will help your music get discovered.',
    tips: [
      { title: 'Optimize for YouTube Music Search', content: 'YouTube Music search behaves differently from main YouTube. Include genre, mood, and instrumental tags. Use "Official Music Video," "Lyric Video," or "Audio" in your title to help YouTube categorize your content correctly.' },
      { title: 'Use Cover Song Titles Strategically', content: 'For cover songs, use the format: "Original Artist - Song Title (Cover by Your Name)." This helps your video appear for searches of the original song. Add "cover" to your first 3 tags.' },
      { title: 'Build Playlists Around Moods and Genres', content: 'Create thematic playlists — "Chill Study Beats," "Workout Motivation," "Sad Songs." Playlists rank in YouTube search and keep viewers watching multiple videos. They also signal topic authority to the algorithm.' },
      { title: 'Thumbnail Consistency Builds Brand', content: 'Use a consistent thumbnail style for your music videos. Include your artist name or logo, use consistent colors/fonts, and feature high-quality imagery. Viewers who recognize your style are more likely to click.' },
      { title: 'Leverage Community Posts for Promotion', content: 'Use YouTube Community posts to share snippets, behind-the-scenes content, and poll fans on what to cover next. Active community engagement signals channel health to the algorithm.' },
      { title: 'Release on a Schedule', content: 'Music audiences are loyal but expect consistency. Announce your upload schedule (e.g., "New cover every Friday") and stick to it. Use Premiere features for major releases to build anticipation.' },
    ],
    stats: { avgCtr: '5-8%', bestLength: '3-5 min', topKeywords: 'song title + official/cover/lyric/music video', avgCpm: '$1.50' },
    related: ['gaming', 'lifestyle', 'education'],
  },
  {
    id: 'fitness', name: 'Fitness & Health Channels', icon: '💪',
    description: 'YouTube SEO for fitness channels — workout videos, nutrition advice, wellness tips, and health content.',
    metaDesc: 'YouTube SEO for fitness channels: optimize workout videos, nutrition guides, and wellness content. Tips on exercise keywords, demonstration thumbnails, and retention strategies.',
    h1: 'YouTube SEO for Fitness Channels: The 2026 Guide',
    intro: 'Fitness content continues to grow on YouTube, with viewers searching for everything from 10-minute workouts to detailed nutrition plans. Standing out requires content that\'s both useful and findable.',
    tips: [
      { title: 'Include Duration and Difficulty in Titles', content: 'Fitness viewers search by workout length and difficulty. Include both in your title: "20 Minute HIIT Workout (Beginner Friendly)" or "45 Minute Full Body Strength (Intermediate)."' },
      { title: 'Use Equipment Tags for Discovery', content: 'Include equipment requirements in your title, description, and tags: "no equipment," "dumbbells only," "resistance bands," "home workout." These are highly searched filters.' },
      { title: 'Structure Workouts with Timestamps', content: 'Include detailed timestamps: warm-up, each exercise, cool-down, and stretches. This improves retention and helps with search ranking.' },
      { title: 'Demonstrate Proper Form in Thumbnails', content: 'Use thumbnails that show correct exercise form, not just your face. A clear demonstration of an exercise mid-movement with good lighting outperforms generic fitness thumbnails.' },
      { title: 'Create Series for Retention', content: 'Fitness viewers love series: "30-Day Abs Challenge," "Beginner to Runner in 8 Weeks." Series structure increases channel watch time and subscriber conversion.' },
      { title: 'Target Recovery and Wellness Keywords', content: 'Beyond workouts, target recovery keywords: "post-workout stretch," "foam rolling routine," "sleep hygiene for athletes." Lower competition than workout keywords.' },
    ],
    stats: { avgCtr: '6-9%', bestLength: '15-30 min', topKeywords: 'workout type + duration/difficulty/equipment', avgCpm: '$4.00' },
    related: ['cooking', 'lifestyle', 'education'],
  },
  {
    id: 'tech-reviews', name: 'Tech Review Channels', icon: '💻',
    description: 'YouTube SEO for tech review channels — gadget reviews, comparisons, unboxings, and tech tutorials.',
    metaDesc: 'YouTube SEO for tech review channels: optimize gadget reviews, comparisons, and unboxings. Tips on product keywords, comparison titles, and thumbnail strategies that drive clicks.',
    h1: 'YouTube SEO for Tech Review Channels: The 2026 Guide',
    intro: 'Tech reviews are among the most searched content on YouTube, but competition from large channels is intense. Success requires targeting the right keywords and creating compelling comparisons.',
    tips: [
      { title: 'Use Product Name + Keyword Format', content: 'Start titles with the exact product name followed by the review type: "iPhone 16 Pro Review: 6 Months Later" or "MacBook Air M4 vs MacBook Pro M4 — Which Should You Buy?"' },
      { title: 'Create Comparison and Versus Content', content: 'Comparison videos ("X vs Y") consistently outperform single-product reviews. They capture viewers who are deciding between products — high-intent traffic.' },
      { title: 'Include Price and Value Signals in Titles', content: 'Include pricing context: "Best Budget Laptop Under $800," "Is the Pro Worth $400 More?" These titles attract viewers in the decision phase.' },
      { title: 'Benchmark Results Drive Authority', content: 'Include benchmark scores, battery test results, and performance metrics. Create dedicated timestamp sections for each benchmark.' },
      { title: 'Update Old Reviews with New Context', content: 'Revisit popular reviews after 6-12 months with updated context: "iPhone 16 Pro Review — Still Worth It in 2026?" YouTube rewards fresh content.' },
      { title: 'Use High-Contrast Product Thumbnails', content: 'Tech thumbnails perform best with the product clearly visible against a contrasting background. Bright, clean lighting signals production quality.' },
    ],
    stats: { avgCtr: '6-10%', bestLength: '8-15 min', topKeywords: 'product name + review/unboxing/vs/comparison', avgCpm: '$8.00' },
    related: ['gaming', 'education', 'business'],
  },
  {
    id: 'education', name: 'Educational Channels', icon: '📚',
    description: 'YouTube SEO for educational channels — tutorials, explainers, documentary-style content, and course promotion.',
    metaDesc: 'YouTube SEO for educational channels: optimize tutorials, explainers, and course content. Tips on keyword targeting, retention strategies, and building authority.',
    h1: 'YouTube SEO for Educational Channels: The 2026 Guide',
    intro: 'Educational content has exploded on YouTube, with viewers turning to the platform for everything from math tutorials to history documentaries. Success requires deep expertise signals.',
    tips: [
      { title: 'Target Question-Based Keywords', content: 'Optimize for "how to," "what is," "why does," "explained." These question-based keywords have clear search intent and lower competition than broad topic keywords.' },
      { title: 'Use Chapters and Timestamps Extensively', content: 'Break your content into 3-5 minute sections with descriptive titles. Chapters improve retention, boost SEO (chapter titles are indexed), and increase average view duration.' },
      { title: 'Include Visual Aids and Diagrams', content: 'Educational content with visual aids retains viewers 60% better than talking-head-only content. Use screen recordings, animated graphs, and illustrated concepts.' },
      { title: 'Create Series That Build On Each Other', content: 'Educational viewers love structured learning. Create series: "Python for Beginners — Part 1, 2, 3..." Series content dramatically increases channel watch time.' },
      { title: 'Optimize for YouTube\'s Course Feature', content: 'Use YouTube\'s course/playlist feature to organize your content into structured curricula. Courses rank separately in search.' },
      { title: 'Cite Sources for E-E-A-T Signals', content: 'Cite your sources, show credentials, reference academic papers or industry reports. YouTube favors authoritative educational content in search results.' },
    ],
    stats: { avgCtr: '5-8%', bestLength: '10-20 min', topKeywords: 'topic + explained/tutorial/beginners/guide/course', avgCpm: '$5.00' },
    related: ['tech-reviews', 'business', 'fitness'],
  },
  {
    id: 'business', name: 'Business & Marketing Channels', icon: '📈',
    description: 'YouTube SEO for business channels — marketing tips, entrepreneurship advice, SaaS tutorials, and business strategy.',
    metaDesc: 'YouTube SEO for business and marketing channels. Optimize entrepreneur content, SaaS tutorials, and business strategy videos.',
    h1: 'YouTube SEO for Business & Marketing Channels: The 2026 Guide',
    intro: 'Business and marketing content targets high-intent viewers looking for solutions to specific problems. Success requires demonstrating authority and providing actionable value.',
    tips: [
      { title: 'Target Problem-Solution Keywords', content: 'Target problem-solution keywords: "how to increase website traffic," "best email marketing tool." Your title should promise a specific outcome.' },
      { title: 'Include Numbers and Data in Titles', content: 'Business audiences respond to data-driven titles: "5 Ways to Increase ROI," "3 Marketing Tools That Saved Us $50K/year." Numbers signal concrete, actionable content.' },
      { title: 'Use Case Studies and Real Examples', content: 'Business content with real case studies, before/after metrics, and specific examples outperforms theoretical advice.' },
      { title: 'Optimize for B2B and B2C Keywords Separately', content: 'B2B keywords: "enterprise software," "SaaS metrics." B2C keywords: "side hustle," "freelance tips." Create separate content strategies for each.' },
      { title: 'Leverage LinkedIn Cross-Promotion', content: 'Cross-promote your videos on LinkedIn with a text summary and link. This drives external traffic and builds your professional audience simultaneously.' },
      { title: 'Create Tool Tutorials and Comparisons', content: 'Business viewers actively search for tool tutorials: "How to Use HubSpot CRM," "Notion vs Asana." These have high commercial intent.' },
    ],
    stats: { avgCtr: '5-8%', bestLength: '8-15 min', topKeywords: 'topic + strategy/tips/how to/guide/tools', avgCpm: '$10.00' },
    related: ['education', 'tech-reviews', 'fitness'],
  },
  {
    id: 'lifestyle', name: 'Lifestyle & Vlog Channels', icon: '✨',
    description: 'YouTube SEO for lifestyle channels — daily vlogs, productivity tips, travel content, and personal development.',
    metaDesc: 'YouTube SEO for lifestyle and vlog channels. Optimize daily vlogs, productivity content, and personal development videos.',
    h1: 'YouTube SEO for Lifestyle & Vlog Channels: The 2026 Guide',
    intro: 'Lifestyle and vlog content is driven by personality and audience connection. While traditional SEO matters, success depends more on browse traffic and recommendations.',
    tips: [
      { title: 'Optimize for Browse Features First', content: 'Lifestyle content gets most views from YouTube browse features (homepage, recommended), not search. Prioritize clickable thumbnails and compelling titles.' },
      { title: 'Use Curiosity Gap Titles for Vlogs', content: 'Vlog titles should create curiosity: "I Quit My Job to Travel Asia — Week 1." These titles work for browse viewers who don\'t know you yet.' },
      { title: 'Build Series for Consistent Views', content: 'Lifestyle series drive repeat viewership: "Morning Routine 2026," "Weekly Vlog #45." Numbered series encourage binge-watching.' },
      { title: 'Thumbnail Focus on Emotion and Reaction', content: 'Lifestyle thumbnails that show genuine emotion outperform posed shots. Candid reactions and authentic moments create stronger click-through.' },
      { title: 'Engage Heavily in Comments', content: 'Reply to comments within the first hour, pin thoughtful responses, and ask questions. High comment engagement signals content quality.' },
      { title: 'Use Community Tab Between Uploads', content: 'Post daily to the Community tab: polls, photos, behind-the-scenes, quick Q&As. Maintains algorithmic momentum between uploads.' },
    ],
    stats: { avgCtr: '8-12%', bestLength: '8-15 min', topKeywords: 'topic + vlog/day in the life/weekly/with me', avgCpm: '$3.50' },
    related: ['cooking', 'fitness', 'music'],
  },
];

export default niches;