// scripts/vs-data.js
// Data-driven comparison engine — generates vs/ pages programmatically
// Each entry defines a tool comparison against YT SEO Architect

const tools = [
  {
    id: 'vidiq',
    name: 'vidIQ',
    url: 'https://vidiq.com',
    pricing: 'Free / $39/mo Pro',
    category: 'SEO & Analytics',
    tagline: 'YouTube keyword research & channel analytics',
    logo: null, // Will use text badge
    features: [
      { name: 'AI Thumbnail Scoring', us: true, them: false },
      { name: 'Keyword Research', us: true, them: true, note: 'vidIQ has extensive keyword DB' },
      { name: 'Title Optimization', us: true, them: true },
      { name: 'Tag Generation', us: true, them: true },
      { name: 'Channel Audit', us: true, them: true },
      { name: 'A/B Title Testing', us: true, them: false },
      { name: 'Competitor Analysis', us: true, them: true },
      { name: 'Trending Alerts', us: false, them: true },
      { name: 'Browser Extension', us: false, them: true },
      { name: 'Price', us: 'Free (unlimited)', them: 'Free / $39/mo' },
    ],
    verdict: 'vidIQ has deeper keyword research and a popular browser extension. YT SEO Architect wins on thumbnail scoring and A/B title testing — both free. Use YT SEO Architect for optimization, vidIQ for discovery.',
    bestFor: 'Creators who want AI thumbnail analysis and title A/B testing without paying.',
    score: { us: 8.5, them: 8.0 },
    related: ['tubebuddy', 'morningfame', 'tubics', 'canva', 'keywordtool'],
  },
  {
    id: 'tubebuddy',
    name: 'TubeBuddy',
    url: 'https://tubebuddy.com',
    pricing: 'Free / $7.20/mo Pro',
    category: 'SEO & Optimization',
    tagline: 'YouTube channel management & optimization',
    features: [
      { name: 'AI Thumbnail Scoring', us: true, them: false },
      { name: 'Keyword Research', us: true, them: true },
      { name: 'Title Optimization', us: true, them: true },
      { name: 'Tag Generation', us: true, them: true },
      { name: 'Channel Audit', us: true, them: true },
      { name: 'A/B Testing', us: true, them: true, note: 'TubeBuddy A/B tests thumbnails' },
      { name: 'Bulk Processing', us: false, them: true },
      { name: 'Browser Extension', us: false, them: true },
      { name: 'Schedule & Publish', us: false, them: true },
      { name: 'Price', us: 'Free (unlimited)', them: 'Free / $7.20/mo' },
    ],
    verdict: 'TubeBuddy is a full channel management suite. YT SEO Architect focuses specifically on video optimization with AI scoring. Best together — TubeBuddy for workflow, YT SEO Architect for optimization intelligence.',
    bestFor: 'Creators who want AI-driven optimization scores and free tools.',
    score: { us: 8.5, them: 8.5 },
    related: ['vidiq', 'morningfame', 'tubics', 'canva', 'keywordtool'],
  },
  {
    id: 'morningfame',
    name: 'Morningfame',
    url: 'https://morningfa.me',
    pricing: 'Free / $5.99/mo',
    category: 'Analytics',
    tagline: 'YouTube analytics simplified',
    features: [
      { name: 'AI Thumbnail Scoring', us: true, them: false },
      { name: 'Keyword Research', us: true, them: false },
      { name: 'Title Optimization', us: true, them: false },
      { name: 'Channel Audit', us: true, them: true },
      { name: 'Growth Analytics', us: false, them: true, note: 'Morningfame specializes in growth insights' },
      { name: 'Tag Generation', us: true, them: false },
      { name: 'Content Ideas', us: false, them: true },
      { name: 'A/B Testing', us: true, them: false },
      { name: 'Price', us: 'Free (unlimited)', them: 'Free / $5.99/mo' },
    ],
    verdict: 'Morningfame provides excellent growth analytics and content ideas. YT SEO Architect offers more hands-on optimization tools like thumbnail scoring and A/B testing. Different tools for different needs.',
    bestFor: 'Creators who want AI optimization tools for free.',
    score: { us: 8.0, them: 7.0 },
    related: ['vidiq', 'tubebuddy', 'tubics', 'canva', 'keywordtool'],
  },
  {
    id: 'tubics',
    name: 'Tubics',
    url: 'https://tubics.com',
    pricing: '$29/mo',
    category: 'SEO & Analytics',
    tagline: 'YouTube SEO & video analytics',
    features: [
      { name: 'AI Thumbnail Scoring', us: true, them: false },
      { name: 'Keyword Research', us: true, them: true },
      { name: 'Title Optimization', us: true, them: true },
      { name: 'Channel Audit', us: true, them: true },
      { name: 'Video SEO Score', us: false, them: true, note: 'Tubics gives each video a SEO score' },
      { name: 'Tag Generation', us: true, them: true },
      { name: 'Competitor Tracking', us: false, them: true },
      { name: 'A/B Testing', us: true, them: false },
      { name: 'Price', us: 'Free (unlimited)', them: '$29/mo' },
    ],
    verdict: 'Tubics offers a solid SEO scoring system and competitor tracking. YT SEO Architect matches most features while staying completely free. If budget is a concern, YT SEO Architect is the better choice.',
    bestFor: 'Creators who want free SEO tools with thumbnail and A/B testing.',
    score: { us: 8.0, them: 7.5 },
    related: ['vidiq', 'tubebuddy', 'morningfame', 'canva', 'keywordtool'],
  },
  {
    id: 'canva',
    name: 'Canva',
    url: 'https://canva.com',
    pricing: 'Free / $13/mo Pro',
    category: 'Design',
    tagline: 'Graphic design platform for thumbnails',
    features: [
      { name: 'AI Thumbnail Scoring', us: true, them: false },
      { name: 'Thumbnail Design', us: false, them: true, note: 'Canva has excellent design tools' },
      { name: 'Title Optimization', us: true, them: false },
      { name: 'Channel Audit', us: true, them: false },
      { name: 'A/B Testing', us: true, them: false },
      { name: 'Tag Generation', us: true, them: false },
      { name: 'Brand Kits', us: false, them: true },
      { name: 'Templates', us: false, them: true },
      { name: 'Keyword Research', us: true, them: false },
      { name: 'Price', us: 'Free (unlimited)', them: 'Free / $13/mo' },
    ],
    verdict: 'Canva designs thumbnails. YT SEO Architect tells you if they will work. Use both together — design in Canva, then optimize with YT SEO Architect.',
    bestFor: 'Creators who design in Canva and want to validate their thumbnails before publishing.',
    score: { us: 8.0, them: 6.5 },
    related: ['vidiq', 'tubebuddy', 'morningfame', 'tubics', 'keywordtool'],
  },
  {
    id: 'keywordtool',
    name: 'Keyword Tool',
    url: 'https://keywordtool.io',
    pricing: 'Free / $69/mo Pro',
    category: 'Keyword Research',
    tagline: 'Keyword research for multiple platforms',
    features: [
      { name: 'AI Thumbnail Scoring', us: true, them: false },
      { name: 'Keyword Research', us: true, them: true, note: 'Keyword Tool covers YouTube + Google + Amazon' },
      { name: 'Title Optimization', us: true, them: false },
      { name: 'Channel Audit', us: true, them: false },
      { name: 'A/B Testing', us: true, them: false },
      { name: 'Tag Generation', us: true, them: false },
      { name: 'Multi-Platform', us: false, them: true },
      { name: 'Search Volume Data', us: false, them: true },
      { name: 'Price', us: 'Free (unlimited)', them: 'Free / $69/mo' },
    ],
    verdict: 'Keyword Tool is excellent for multi-platform keyword research. YT SEO Architect combines keyword research with optimization tools (thumbnail scoring, title A/B testing) in one free platform. Better value for YouTube-specific creators.',
    bestFor: 'YouTube creators who want all-in-one optimization without paying for multiple tools.',
    score: { us: 8.0, them: 7.0 },
    related: ['vidiq', 'tubebuddy', 'morningfame', 'tubics', 'canva'],
  },
];

export default tools;